version: "3.8"

services:
  bluesky-pds:
    #image: docker.nexthouse.org/knockthedoor/bluesky-atproto-pds:latest
    image: docker.nexthouse.org/knockthedoor/bluesky-pds:latest
    container_name: bluesky-pds
    restart: unless-stopped
    ports:
      - "2583:2583"
    env_file:
      - .env
    volumes:
      - ./pds:/pds
      - ./pds-data:/pds-data
    user: root
    command: ["node", "--enable-source-maps", "index.js"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2583/xrpc/app.bsky.actor.getProfile?actor=bsky.app"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    


